{ inputs, ... }:
{
  flake.modules.homeManager.packages =
    { pkgs, ... }:
    {
      home.packages = [
        inputs.mbnvim.packages.${pkgs.system}.default
        pkgs.coreutils
        pkgs.eza
        pkgs.bat
        pkgs.ack
        pkgs.fd
        pkgs.fswatch
        pkgs.fzf
        pkgs.tree
        pkgs.ripgrep
        pkgs.jq
        pkgs.yq
        pkgs.delta
        pkgs.gnupg
        pkgs.ffmpeg
        pkgs.graphviz
        pkgs.imagemagick
        pkgs.kitty
        pkgs.gh
        pkgs.awscli2
        pkgs.aws-sam-cli
        pkgs.pipx
        pkgs.uv
        pkgs.presenterm
        pkgs.nixpkgs-review
        pkgs.nix-output-monitor
        pkgs.glow
        pkgs.gonzo
        pkgs.trufflehog
        pkgs.aws-vault
        pkgs.okta-aws-cli
        pkgs.hyperfine
        pkgs.nixfmt
        pkgs.nix-tree
        pkgs.rainfrog
        pkgs.fastfetch
        pkgs.speedtest-cli
        pkgs._1password-cli
        pkgs.shellcheck
        pkgs.aws-sso-util
        pkgs.awscurl
        pkgs.rain
        pkgs.cfn-transform
        pkgs.former
        pkgs.aws-whoami
        pkgs.mergiraf
      ];
    };
}
