#!/usr/bin/env zsh

for file in ~/.config/zsh/custom/*(N); do
  [ -f "$file" ] && source "$file" 2>/dev/null
done

setopt share_history
setopt inc_append_history
setopt prompt_subst

bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

_git_branch() {
  local branchname
  branchname="$(git --no-optional-locks rev-parse --abbrev-ref HEAD 2>/dev/null)" || return 0
  if [ -z "$(git --no-optional-locks status --porcelain --untracked-files=normal 2>/dev/null | head -1)" ]; then
    printf "%%F{green}($branchname ✔)"
  else
    printf "%%F{red}($branchname ✘)"
  fi
}
_aws_region() {
    if [ $AWS_REGION ]; then
        printf "%%F{magenta}($AWS_REGION)"
    fi
}
_aws_profile() {
    if [ $AWS_PROFILE ]; then
        printf "%%F{blue}($AWS_PROFILE%%F{blue})"
    elif [ $AWSUSE_PROFILE ]; then
        printf "%%F{blue}($AWSUSE_PROFILE%%F{blue})"
    elif [ $AWSUME_PROFILE ]; then
        printf "%%F{blue}($AWSUME_PROFILE"
        if [ $AWSUME_EXPIRATION ]; then
            EXPIRATION=$(date -d $AWSUME_EXPIRATION +"%H:%M:%S")
            EXP_SECONDS=(`date -d $AWSUME_EXPIRATION +"%s"`)
            NOW_SECONDS=(`date +%s`)
            DIFF=$((EXP_SECONDS - NOW_SECONDS))
            if ((DIFF < 60)); then
                COLOR="%%F{red}"
              elif ((DIFF < 300)); then
                COLOR="%%F{yellow}"
            else
                COLOR="%%F{green}"
            fi
            printf "|"
            printf "$COLOR$EXPIRATION"
        fi
        printf "%%F{blue})"
    fi
}
_exit_status() {
    if [ $EXIT_STATUS -eq 0 ]; then
        printf "%%F{green}✔%%f"
    else
        printf "%%F{red}✘ $EXIT_STATUS%%f"
    fi
}

precmd() {
    EXIT_STATUS=$?
}
NEWLINE=$'\n'
PROMPT='%F{yellow}➜'
PROMPT+=' %F{cyan}%*'
PROMPT+=' $(_exit_status)'
PROMPT+=' $(_aws_region)'
PROMPT+='$(_aws_profile)'
PROMPT+='$(_git_branch)'
PROMPT+=' %F{cyan}%~'
PROMPT+='${NEWLINE}$ '
export RPROMPT=""

export LESS="-F -X -R"
export PYTHONDONTWRITEBYTECODE=1
export PIPENV_VENV_IN_PROJECT=true
export EDITOR=nvim
export ZLE_REMOVE_SUFFIX_CHARS="" # stop zsh from eating space before |

alias zsh-benchmark="hyperfine --style color 'zsh -i -c exit'"
alias back="cd -"
alias ls="eza"
alias cat="bat --theme auto:system"
alias echo-path="echo $PATH | tr : '\n'"
alias awsid="aws sts get-caller-identity --query Account --output text"
alias ytdl="yt-dlp -f \"bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best\""
alias tf="terraform"
alias tms="~/.local/bin/tmux-sessionizer.sh"
alias tmn="~/.local/bin/tmux-new-session.sh"
alias awsume="source awsume"
alias awsumel="source awsume --role-duration 43200"
alias awsumer="source awsume \${AWSUME_COMMAND}";
alias icat="kitten icat --align left"
alias idot="dot -Tsvg | kitten icat --align left"
alias flush-mac-dns="sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder"
alias docker="finch"

complete -C 'aws_completer' aws

eval "$(command fzf --zsh)"
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
