# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.luks.devices."luks-8a9abb95-5cd1-43bb-9446-cf4dc9a76aea".device =
    "/dev/disk/by-uuid/8a9abb95-5cd1-43bb-9446-cf4dc9a76aea";

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-6adc3b1a-2467-4980-8f6c-54e3a6a104bb";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-6adc3b1a-2467-4980-8f6c-54e3a6a104bb".device =
    "/dev/disk/by-uuid/6adc3b1a-2467-4980-8f6c-54e3a6a104bb";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AEF3-4A9F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-8a9abb95-5cd1-43bb-9446-cf4dc9a76aea"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
