#!/usr/bin/env bash

function git-branches() {
  git for-each-ref \
    --sort=committerdate refs/heads/ \
    --format='%(align:40)%(refname:short)%(end) # %(authorname) %(committerdate:relative)'
}

cleanup() {
  file=${1}
  sed 's/#.*//g' "${file}" | sed '/&$/d'
}

git-branches > /tmp/branches-raw
cleanup /tmp/branches-raw > /tmp/branches-raw-clean
cp /tmp/branches-raw /tmp/branches-edited
vi /tmp/branches-edited
cleanup /tmp/branches-edited > /tmp/branches-edited-clean
grep -v "$(cat /tmp/branches-edited-clean)" < /tmp/branches-raw-clean > /tmp/branches
xargs git branch -D < /tmp/branches
