name: build

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: assume role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::792172458894:role/github-actions
          role-session-name: GitHubActions-${{ github.run_id }}
      - name: get signing key
        run: |
          secret=$(aws secretsmanager get-secret-value \
            --secret-id /nix/cache/signing-key \
            --query SecretString \
            --output text)
          private_key=$(echo "$secret" | jq -r '.privateKey')
          public_key=$(echo "$secret" | jq -r '.publicKey')
          echo "::add-mask::${private_key}"
          echo "$private_key" > private-key
          chmod 600 private-key
          echo "public key: ${public_key}"
          echo "PUBLIC_KEY=${public_key}" >> "$GITHUB_ENV"
      - name: install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          install_url: https://releases.nixos.org/nix/nix-2.28.4/install
          extra_nix_config: |
            trusted-public-keys = ${{ env.PUBLIC_KEY }} cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://nix.barney.dev/ https://cache.nixos.org/
      - name: build system.nix darwin configuration
        run: |
          nix build --quiet .#darwinConfigurations.aarch64.system
      - name: assume role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::792172458894:role/github-actions
          role-session-name: GitHubActions-${{ github.run_id }}
      - name: sign and upload to cache
        run: |
          nix store sign --verbose --key-file ./private-key --recursive ./result
          nix copy --quiet --max-jobs auto --to "s3://nix.barney.dev?region=us-east-2" ./result
          echo "successfully uploaded to cache at s3://nix.barney.dev"
