name: update-nixpkgs

on:
  schedule:
    # Runs every Monday at 6:00 AM EST (11:00 AM UTC)
    - cron: '0 11 * * 1'
  workflow_dispatch: {}

jobs:
  update-nixpkgs:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: update nixpkgs flake input
        run: |
          nix flake update nixpkgs
          echo "NIXPKGS_REV=$(nix flake metadata --json | jq -r '.locks.nodes.nixpkgs.locked.rev')" >> "$GITHUB_ENV"
      - name: create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="chore/update-nixpkgs-$(date +%Y%m%d)"
          git checkout -b "$BRANCH_NAME"
          git add flake.lock
          git commit -m "Update nixpkgs to ${NIXPKGS_REV:0:7}"
          git push origin "$BRANCH_NAME"
          gh pr create \
            --title "Update nixpkgs to ${NIXPKGS_REV:0:7}" \
            --body "Update nixpkgs to ${NIXPKGS_REV}"
